### ISSUE TITLE
Integrate with mikro-orm

### ISSUE THREAD

**Issue by rubiin** [SoftwareBrothers/adminjs-nestjs#16]
Hi there currently using mikro-orm which is so awesome alongside nestjs. Is there a way to use it with mikro-orm.
reference: https://mikro-orm.io/

**Comment by rubiin** [comment]
someone has started the work at https://github.com/dziraf/admin-bro-mikroorm/ . Also any eta on fastify support

**Comment by dziraf** [comment]
Our example app repository will soon be updated with more usage examples. Currently you can see NestJS examples here:
https://github.com/SoftwareBrothers/adminjs-example-app/tree/typescript-version/src/servers/nestjs

**Comment by yackinn** [comment]
```ts
imports: [
AdminModule.createAdminAsync({
      inject: [MikroORM],
      useFactory: async (orm: MikroORM) => {
        return {
          adminJsOptions: {
            rootPath: '/admin',
            resources: [
              {
                resource: {
                  model: User,
                  orm,
                },
              }
            ]
          }
        };
      }
    }),
]
```

You also have to set `allowGlobalContext: true` in the config.
The mikroorm documentation that this option shouldn't be set to true though

**Comment by rubiin** [comment]
> Our example app repository will soon be updated with more usage examples. Currently you can see NestJS examples here: https://github.com/SoftwareBrothers/adminjs-example-app/tree/typescript-version/src/servers/nestjs

the link is broken

**Comment by rubiin** [comment]
@yackinn do you have a sample app?
