### ISSUE TITLE
Incompatible with nestjs 8

### ISSUE THREAD

**Issue by flamewow** [SoftwareBrothers/adminjs-nestjs#26]
```
ERROR [ExceptionHandler] Nest can't resolve dependencies of the AdminModule (?, AbstractLoader, CONFIG_TOKEN). Please make sure that the argument HttpAdapterHost at index [0] is available in the AdminModule context.

Potential solutions:
- If HttpAdapterHost is a provider, is it part of the current AdminModule?
- If HttpAdapterHost is exported from a separate @Module, is that module imported within AdminModule?
  @Module({
    imports: [ /* the Module containing HttpAdapterHost */ ]
  })

```

**Comment by tomasz-jankowski** [comment]
Temporary workaround is to implement AdminJS as in standard Express application:
[https://adminjs.co/tutorial-installation-instructions.html](Installation instructions)

**Comment by mkayander** [comment]
It's a strange issue. Nest cannot provide any dependency injection for AdminModule constructor. While the module's code seems fine. I tried updating Nest version in this package and rebuild, but no success. Does anyone have any ideas? Maybe it builds wrong?

**Comment by mkayander** [comment]
Another temporary solution: 
- Copy contents of /src directory to your own separate 'admin' directory (module). 
- Import `AdminModule` from there.
- Now it just works.

So as i said i assume the issue is somehow not in the source code itself but in the way it compiles and delivers as a package.

**Comment by apperside** [comment]
the problem still persists with v3.0.0, this is my dependencies:
```

    "@adminjs/express": "^4.0.0",
    "@adminjs/nestjs": "^3.0.0",
    "@adminjs/typeorm": "^2.0.0",
    "@nestjs/axios": "^0.0.1",
    "@nestjs/common": "^8.0.7",
    "@nestjs/config": "^1.0.1",
    "@nestjs/core": "^8.0.7",
    "@nestjs/jwt": "^8.0.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/passport": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/platform-socket.io": "^8.0.6",
    "@nestjs/swagger": "^5.0.8",
    "@nestjs/typeorm": "^8.0.1",
    "@nestjs/websockets": "^8.0.6",
    "@nestjsx/crud": "^4.6.2",
    "@nestjsx/crud-typeorm": "^4.6.2",

```

This is my AppModule
<img width="790" alt="Screenshot 2021-09-27 at 15 35 00" src="https://user-images.githubusercontent.com/5955338/134919045-558c4f38-6de6-4a05-9c93-725b7e5da963.png">

This is my run output
<img width="1165" alt="Screenshot 2021-09-27 at 15 35 57" src="https://user-images.githubusercontent.com/5955338/134919190-5e3e7646-44ec-42bd-a452-82e85ea80654.png">

**Comment by sepehr09** [comment]
i have same problem.

**Comment by sepehr09** [comment]
the problem still persists with v3.0.1
