### ISSUE TITLE
Wrong function type at AdminModuleOptions.auth.authenticate interface 

### ISSUE THREAD

**Issue by mkayander** [SoftwareBrothers/adminjs-nestjs#30]
At `admin-module-options.interface.ts:24` there's a line:
```authenticate: (email: string, password: string) => Promise<CurrentAdmin>```
The promise return type does not make sense. It should be nullable.
Let's see the usage of this function at `login.handler.ts:39`:
```
const adminUser = await auth.authenticate(email, password);
    if (adminUser) {
      req.session.adminUser = adminUser;
      req.session.save((err) => {
        if (err) {
          next(err);
        }
        if (req.session.redirectTo) {
          res.redirect(302, req.session.redirectTo);
        } else {
          res.redirect(302, rootPath);
        }
      });
    } else {
      const login = await admin.renderLogin({
        action: admin.options.loginPath,
        errorMessage: "invalidCredentials",
      });
      res.send(login);
    }
```
It checks if the result of the function is falsy (nullish). Yet the compiler won't run if we return undefined or null because of the wrong type at the interface.

The correct function type would be:
```authenticate: (email: string, password: string) => Promise<CurrentAdmin | null>```

**Comment by mkayander** [comment]
Pushed a PR that would fix this issue with no side effects. Would be glad if it gets approved! 🙂

**Comment by synic** [comment]
@dziraf , @wojtek-krysiak can someone take a look at this? Is there another way to return something to tell the server that the admin failed to login?
